spring:
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: "a01091522550@gmail.com"
    password: "uybvukhwxyoekenu"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


