spring:
  datasource:
    #url: jdbc:mariadb://localhost:3306/newsapp
    url: jdbc:mariadb://mydb.c8xuw45xrre9.ap-northeast-2.rds.amazonaws.com/newsapp
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: wjd@568099