
server:
  tomcat:
    max-http-form-post-size: 6291456

spring:
  #JPA 설정
  jpa:
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true

  datasource:
    #url: jdbc:mariadb://localhost:3306/newsapp
    url: jdbc:mysql://sasa5680azure.mysql.database.azure.com:3306/newsapp
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sas5680
    password: wjd@568099



  servlet:
    multipart:
      max-file-size: 8MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    host: 13.125.219.49
    port: 6379

  server:
    port: 8080

  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    username: "a01091522550@gmail.com"
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400
  access-token-validity-in-seconds: 1800 # 초 단위
  refresh-token-validity-in-seconds: 604800

springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
  paths-to-match:
    - /api/**

cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    s3:
      bucket: opennewsapp
    region:
      static: ap-northeast-2
    stack:
      auto: false

